### ISSUE TITLE
Crash durring payout

### ISSUE THREAD

**Issue by s-fleck** [root676/G08_python_for_geosciences#4]
Hmm bei mir crashed er noch immer... hier mal was ich gemacht habe:

```
How much money do want to bring to the table? 900

Choose an option you want to bet on. (use the number between the parenthesis)
The numbers in [ ] represent the payout of each bet.
  (1) 'Straight' or 'Single'        : bet on a single number [35 to 1]
  (2) 'Manque' or 'Passe'           : bet on the first 18 {1-18} or second 18 {19-36} numbers. [1 to 1]
  (3) 'Rouge ou Noir' (Red or Black): bet on which color the roulette wheel will show. [1 to 1]
  (4) 'Pair ou Impair' (Even or odd): bet on even or odd numbers (without 0). [1 to 1]
  (5) 'Dozen Bets'                  : bet on the first dozen {1-12}, second dozen {13-24} or third dozen {25-36} numbers. [2 to 1]
  (6) 'Column Bets'                 : bet on one of the three vertical lines e.g.: 1-4-7-10 . . . [2 to 1]

  (7) Stop playing
1
You are betting on a single number.
Choose a number between 0 and 36: 3
How much money do want to bet?: 2
To you want to bet on another option? (y/n): y

Choose an option you want to bet on. (use the number between the parenthesis)
The numbers in [ ] represent the payout of each bet.
  (1) 'Straight' or 'Single'        : bet on a single number [35 to 1]
  (2) 'Manque' or 'Passe'           : bet on the first 18 {1-18} or second 18 {19-36} numbers. [1 to 1]
  (3) 'Rouge ou Noir' (Red or Black): bet on which color the roulette wheel will show. [1 to 1]
  (4) 'Pair ou Impair' (Even or odd): bet on even or odd numbers (without 0). [1 to 1]
  (5) 'Dozen Bets'                  : bet on the first dozen {1-12}, second dozen {13-24} or third dozen {25-36} numbers. [2 to 1]
  (6) 'Column Bets'                 : bet on one of the three vertical lines e.g.: 1-4-7-10 . . . [2 to 1]

  (7) Stop playing
2
Your are betting on the first 18 or second 18 numbers:Please decide on which set you want to bet (use the number between the parenthesis):
  (1) Manque - first 18 {1-18}
  (2) Passe - second 18 {19-26}1
How much money do want to bet?: 30
To you want to bet on another option? (y/n): y

Choose an option you want to bet on. (use the number between the parenthesis)
The numbers in [ ] represent the payout of each bet.
  (1) 'Straight' or 'Single'        : bet on a single number [35 to 1]
  (2) 'Manque' or 'Passe'           : bet on the first 18 {1-18} or second 18 {19-36} numbers. [1 to 1]
  (3) 'Rouge ou Noir' (Red or Black): bet on which color the roulette wheel will show. [1 to 1]
  (4) 'Pair ou Impair' (Even or odd): bet on even or odd numbers (without 0). [1 to 1]
  (5) 'Dozen Bets'                  : bet on the first dozen {1-12}, second dozen {13-24} or third dozen {25-36} numbers. [2 to 1]
  (6) 'Column Bets'                 : bet on one of the three vertical lines e.g.: 1-4-7-10 . . . [2 to 1]

  (7) Stop playing
2
Your are betting on the first 18 or second 18 numbers:Please decide on which set you want to bet (use the number between the parenthesis):
  (1) Manque - first 18 {1-18}
  (2) Passe - second 18 {19-26}2
How much money do want to bet?: 30
To you want to bet on another option? (y/n): y

Choose an option you want to bet on. (use the number between the parenthesis)
The numbers in [ ] represent the payout of each bet.
  (1) 'Straight' or 'Single'        : bet on a single number [35 to 1]
  (2) 'Manque' or 'Passe'           : bet on the first 18 {1-18} or second 18 {19-36} numbers. [1 to 1]
  (3) 'Rouge ou Noir' (Red or Black): bet on which color the roulette wheel will show. [1 to 1]
  (4) 'Pair ou Impair' (Even or odd): bet on even or odd numbers (without 0). [1 to 1]
  (5) 'Dozen Bets'                  : bet on the first dozen {1-12}, second dozen {13-24} or third dozen {25-36} numbers. [2 to 1]
  (6) 'Column Bets'                 : bet on one of the three vertical lines e.g.: 1-4-7-10 . . . [2 to 1]

  (7) Stop playing
3
Your are betting on 'red' or 'black'. 
Please decide on which you want to bet (red/black): red
How much money do want to bet?: 30
To you want to bet on another option? (y/n): n

The roulette stopped at number 32 !
('You have won {} Euro', 60.0)
Traceback (most recent call last):
  File "main.py", line 16, in <module>
RouletteTable().starting_playing()
  File "/home/hoelk/Dropbox/workspace/py/roulette_table/homework1/roulettetable.py", line 83, in starting_playing
self.payout_phase()
  File "/home/hoelk/Dropbox/workspace/py/roulette_table/homework1/roulettetable.py", line 267, in payout_phase
won_money += self.playerOnTable.wins(self.winning_quote(mainoption)*money)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by Coldrunner** [comment]
hey, hab das jetzt mit deinen angaben gemacht, aber scheint zu funktionieren. Vllt. habe ich zufällig den Fehler ausgebessert, aber probiere es einfach vorsichtshalber nochmal
